# Generated by Django 4.2.30 on 2026-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('quantity', models.IntegerField(default=0, verbose_name='在庫数')),
            ],
        ),
    ]
