# Generated by Django 4.2.30 on 2026-08-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫')], max_length=3, verbose_name='種別')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
        ),
    ]
